markdown: kramdown

lang:
  - en
  - es

baseurl: /

# URL of the Site
url: 'https://joseeelv.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jose's Portfolio
# Description of the Site
description: Welcome to my hacking website
# URL of Image of the Site
site-image: "/assets/images/favicon.png"
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: "/assets/images/favicon.png"
# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "/assets/images/banner.png"
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jose.venegasan@gmail.com
github_username: Joseeelv
linkedin_username: jose-luis-venega-sánchez-817a65285
# twitter_username: thedevslot
# instagram_username: joseelv_
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Jose Luis Venega
# URL for the Image of the Author
author-image: "/assets/images/me.png"
# 60 Words About the Author
author-about: Hi! I'm Jose Luis Venega, a Computer Engineering student at the University of Cádiz. Alongside my studies, I focus on enhancing my skills in ethical hacking, with a particular emphasis on penetration testing. I dedicate my time to solving practical labs and challenges on platforms such as Hack The Box and VulnHub, while also actively participating in CTF competitions, where I apply my expertise in cybersecurity and technical problem-solving.


# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)ZZ
author-url: https://github.com/Joseeelv

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

collections:
  projects:
    output: true

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
